### ISSUE TITLE
How to clear chat sdk ?

### ISSUE THREAD

**Issue by prebhas** [microsoft/omnichannel-sdk#23]
I am initializing the chat in login and app logs out .ON logging in again the chatSDK is initialized again and i get following message .
TypeError: Cannot read property 'logEvent' of undefined
    at Function.AriaTelemetry.info (AriaTelemetry.js:67)
    at ScenarioMarker.startScenario (ScenarioMarker.js:43)
    at OmnichannelChatSDK.<anonymous> (OmnichannelChatSDK.js:130)
    at step (OmnichannelChatSDK.js:45)
    at Object.next (OmnichannelChatSDK.js:26)
    at OmnichannelChatSDK.js:20
    at tryCallTwo (core.js:45)
    at doResolve (core.js:200)
    at new Promise (core.js:66)
    at __awaiter (OmnichannelChatSDK.js:16)

**Comment by xTEddie** [comment]
> I am initializing the chat in login and app logs out .ON logging in again the chatSDK is initialized again and i get following message .
> TypeError: Cannot read property 'logEvent' of undefined
> at Function.AriaTelemetry.info (AriaTelemetry.js:67)
> at ScenarioMarker.startScenario (ScenarioMarker.js:43)
> at OmnichannelChatSDK. (OmnichannelChatSDK.js:130)
> at step (OmnichannelChatSDK.js:45)
> at Object.next (OmnichannelChatSDK.js:26)
> at OmnichannelChatSDK.js:20
> at tryCallTwo (core.js:45)
> at doResolve (core.js:200)
> at new Promise (core.js:66)
> at __awaiter (OmnichannelChatSDK.js:16)

@prebhas Omnichannel Chat SDK issues should be opened on https://github.com/microsoft/omnichannel-chat-sdk. This bug was recently fixed as of [v0.3.1-main.5b57f35](https://www.npmjs.com/package/@microsoft/omnichannel-chat-sdk/v/0.3.1-main.5b57f35). Please open an issue in Omnichannel Chat SDK if the issue still occurs. Thanks!
